{
 "title": "MongoDB Metrics",
 "description": "MongoDB Prometheus Exporter Dashboard",
 "tags": [ "MongoDB" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "vAppName",
    "label": "Mongo instance",
    "query": "RPT Production MongoDB, RPT Staging MongoDB"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Query Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "env" },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{job=\"$vAppName\"}[$interval])",
     "legendFormat": "{{legacy_op_type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_document{job=\"$vAppName\"}[$interval])",
     "legendFormat": "{{doc_op_type}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_queryExecutor_scanned{job=\"$vAppName\"}[$interval])",
     "legendFormat": "Scanned"
    },
    {
     "expr": "rate(mongodb_ss_metrics_queryExecutor_scannedObjects{job=\"$vAppName\"}[$interval])",
     "legendFormat": "Scanned Objects"
    }
   ]
  },
  { "title": "Health metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "env" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_ss_uptime{job=\"$vAppName\"}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"available\", job=\"$vAppName\"}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"current\", job=\"$vAppName\"}"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mongodb_ss_mem_virtual{job=\"$vAppName\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "mongodb_ss_mem_resident{job=\"$vAppName\"}",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_network_bytesIn{job=\"$vAppName\"}[$interval])",
     "legendFormat": "Bytes In"
    },
    {
     "expr": "rate(mongodb_ss_network_bytesOut{job=\"$vAppName\"}[$interval])",
     "legendFormat": "Bytes Out"
    }
   ]
  },
  { "title": "Disk Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Disk Reads Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_sys_disks_sda_reads{job=\"$vAppName\"}[$interval])",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Writes Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_sys_disks_sda_writes{job=\"$vAppName\"}[$interval])",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  }
 ]
}