FROM armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/grafana/grafana:5.4.3

COPY services/grafana/datasource-prometheus.yaml /etc/grafana/provisioning/datasources/
COPY services/grafana/dashboard-provider.yaml /etc/grafana/provisioning/dashboards/

COPY services/grafana/production-dashboards/docker-metrics-dashboard.json /var/lib/grafana/dashboards/common/
COPY services/grafana/production-dashboards/mongo-metrics-dashboard.json /var/lib/grafana/dashboards/common/
COPY services/grafana/production-dashboards/prometheus-metrics-dashboard.json /var/lib/grafana/dashboards/common/
COPY services/grafana/production-dashboards/express-rpt-metrics-dashboard.json /var/lib/grafana/dashboards/rpt/

ARG GRAFANA_VIEWER_PASSWORD
ENV GRAFANA_VIEWER_PASSWORD=${GRAFANA_VIEWER_PASSWORD}
ARG GRAFANA_ADMIN_PASSWORD
ENV GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

COPY services/grafana/init.sh .
USER root
RUN sed -i.bak 's/\r$//' ./init.sh
RUN sh ./init.sh
