global:
  scrape_interval: 30s
  external_labels:
    monitor: 'local-monitor'

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: 'Prometheus'
    metrics_path: /metrics
    static_configs:
    - targets: ['172.17.0.1:9090']

  - job_name: 'RPT Production Express'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['rpt.ews.gic.ericsson.se']

  - job_name: 'RPT Production MongoDB'
    metrics_path: /mongo-exporter/metrics
    static_configs:
      - targets: ['rpt.ews.gic.ericsson.se']

  - job_name: 'RPT Production Nginx'
    metrics_path: /metrics
    static_configs:
      - targets: ['rpt.ews.gic.ericsson.se:9113']

  - job_name: 'RPT Production cAdvisor'
    metrics_path: /cadvisor/metrics
    static_configs:
      - targets: ['rpt.ews.gic.ericsson.se']

  - job_name: 'RPT Production Node Exporter'
    metrics_path: /node-exporter/metrics
    static_configs:
      - targets: ['rpt.ews.gic.ericsson.se']

  - job_name: 'RPT Staging Express'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['rpt-staging.ews.gic.ericsson.se']

  - job_name: 'RPT Staging MongoDB'
    metrics_path: /mongo-exporter/metrics
    static_configs:
      - targets: ['rpt-staging.ews.gic.ericsson.se']

  - job_name: 'RPT Staging Nginx'
    metrics_path: /metrics
    static_configs:
      - targets: ['rpt-staging.ews.gic.ericsson.se:9113']

  - job_name: 'RPT Staging cAdvisor'
    metrics_path: /cadvisor/metrics
    static_configs:
      - targets: ['rpt-staging.ews.gic.ericsson.se']

  - job_name: 'RPT Staging Node Exporter'
    metrics_path: /node-exporter/metrics
    static_configs:
      - targets: ['rpt-staging.ews.gic.ericsson.se']

  - job_name: 'METRICS PROD cAdvisor'
    metrics_path: /metrics
    static_configs:
      - targets: ['cAdvisor:8080']

  - job_name: 'METRICS PROD Node Exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['nodeExporter:9100']
